// Excel exports with the report header the specification asks for:
// title, date range, generation time, filters, generated by, column definitions.
import * as XLSX from 'xlsx';
import { me } from './logic.js';

export function exportXlsx({ title, range = '', filters = '', columns, rows, definitions = {} , fileName }) {
  const u = me();
  const head = [
    [title], ['Course', 'Year 3 Preclinical Conservative Dentistry — Faculty of Dentistry, Cairo University'],
    ['Reporting period', range || 'All records to date'], ['Filters', filters || 'None'],
    ['Generated', new Date().toLocaleString('en-GB')], ['Generated by', u ? `${u.name} (${u.role})` : ''],
    ['Confidential', 'Contains student academic records — share only with authorised staff.'], [],
    columns.map((c) => c.label),
  ];
  const body = rows.map((r) => columns.map((c) => (typeof c.get === 'function' ? c.get(r) : r[c.key]) ?? ''));
  const ws = XLSX.utils.aoa_to_sheet([...head, ...body]);
  ws['!cols'] = columns.map((c) => ({ wch: Math.max(10, Math.min(48, (c.label || '').length + 4, c.w || 16)) }));
  const wb = XLSX.utils.book_new();
  XLSX.utils.book_append_sheet(wb, ws, 'Report');
  const defs = columns.map((c) => [c.label, definitions[c.key] || c.def || '']);
  XLSX.utils.book_append_sheet(wb, XLSX.utils.aoa_to_sheet([['Column', 'Definition'], ...defs]), 'Column definitions');
  const name = (fileName || title).replace(/[^\w\- ]+/g, '').replace(/\s+/g, '_') + '_' + new Date().toISOString().slice(0, 10) + '.xlsx';
  XLSX.writeFile(wb, name);
  return name;
}

export async function readRosterFile(file) {
  const buf = await file.arrayBuffer();
  const wb = XLSX.read(buf, { type: 'array' });
  const rows = XLSX.utils.sheet_to_json(wb.Sheets[wb.SheetNames[0]], { header: 1, defval: '' });
  return rows;
}

// Detect columns in a faculty roster sheet (Arabic or English headers).
export function parseRoster(rows) {
  const norm = (s) => String(s || '').trim().toLowerCase();
  let hi = rows.findIndex((r) => r.some((c) => /الكود|code|الاسم|name|email|البريد/.test(norm(c))));
  if (hi < 0) hi = 0;
  const h = rows[hi].map(norm);
  const find = (...re) => h.findIndex((c) => re.some((x) => x.test(c)));
  const ci = { code: find(/الكود/, /^code/, /student.?(no|number|id)/, /رقم/), name: find(/الاسم/, /name/), email: find(/email/, /البريد/, /mail/), section: find(/section/, /sec/, /سكشن/, /مجموعة/, /group/), status: find(/حالة/, /status/) };
  const out = [], problems = [];
  for (const r of rows.slice(hi + 1)) {
    const code = String(r[ci.code] ?? '').trim();
    if (!code || !/^\d{5,}$/.test(code)) continue;
    const rec = { code, name: String(r[ci.name] ?? '').trim(), email: ci.email >= 0 ? String(r[ci.email] ?? '').trim().toLowerCase() : '', section: ci.section >= 0 ? Number(String(r[ci.section]).replace(/\D/g, '')) || null : null, status: ci.status >= 0 ? String(r[ci.status] ?? '').trim() : '' };
    if (!rec.email) problems.push(`${code}: no email`);
    if (!rec.section) problems.push(`${code}: no section`);
    out.push(rec);
  }
  return { students: out, columns: ci, problems };
}
